import { Inter } from "next/font/google";
import "./globals.css";
import { Header, Footer } from "@/components";
import { DesignProvider } from "@/context/design";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <DesignProvider>
          <Header />
          {children}
          <Footer />
        </DesignProvider>
      </body>
    </html>
  );
}
